#!/usr/bin/env python3
"""Batch translate Chinese UI text to English in all source files."""
import os
from pathlib import Path

SRC_DIR = Path(__file__).parent.parent / "src"

# Longest-match-first: sorted by length desc at replacement time
TRANSLATIONS = {
    # ============== LONG PHRASES ==============
    '会话状态异常，请返回上一步重新发送验证码': 'Session state error, please go back and resend verification code',
    '打开浏览器失败，请手动打开链接': 'Failed to open browser, please open the link manually',
    '此邮箱尚未注册 Devin 账号。是否立即通过邮箱验证码注册新账号？需要在下一步设置密码。': 'This email is not registered for a Devin account. Register a new account via email verification code now? You will need to set a password in the next step.',
    '此账号可以通过邮箱验证码登录，无需密码。是否立即发送验证码？': 'This account can log in via email verification code without a password. Send verification code now?',
    '可以尝试用邮箱验证码登录。若邮箱仍收不到验证码，请改用「Refresh Token」模式。': 'You can try logging in with email verification code. If you still cannot receive the code, please use "Refresh Token" mode instead.',
    '确定要将 ${selectedIds.length} 个账户的订阅转让给对应的目标邮箱吗？\\n\\n转让后源账户将被移出团队，此操作不可撤销！': 'Are you sure you want to transfer subscriptions of ${selectedIds.length} accounts to the target emails?\\n\\nSource accounts will be removed from the team after transfer. This action cannot be undone!',
    '请在下方输入对应数量的目标邮箱（每行一个），转让后源账户将被移出团队。': 'Enter the corresponding number of target emails below (one per line). Source accounts will be removed from the team after transfer.',
    '开启伟哥功能将安装 MCP 服务器和全局规则，是否继续？': 'Enabling this feature will install MCP server and global rules. Continue?',
    '关闭伟哥功能将删除 MCP 配置和全局规则，是否继续？': 'Disabling this feature will remove MCP configuration and global rules. Continue?',
    '请输入有效的邮箱地址': 'Please enter a valid email address',
    '组织选择后创建账号失败': 'Failed to create account after organization selection',
    '需要选择组织': 'Organization selection required',
    '已取消多组织选择': 'Multi-organization selection cancelled',
    '获取账号信息失败': 'Failed to get account info',
    '获取用户详情失败': 'Failed to get user details',
    '请输入验证码': 'Please enter verification code',
    '已复制到剪贴板': 'Copied to clipboard',
    '更新账号信息': 'Update account info',
    '已是最新版本': 'Already the latest version',
    '请输入邮箱': 'Please enter email',
    '请输入密码': 'Please enter password',
    '密码长度至少': 'Password must be at least',
    '备注名称最多': 'Nickname max',
    '已在浏览器': 'Opened in browser',
    '打开链接失败': 'Failed to open link',
    '更换计划失败': 'Failed to change plan',
    '没有成功导入任何账号': 'No accounts were imported successfully',
    '请输入有效的邮箱地址': 'Please enter a valid email address',
    '验证码已发送至': 'Verification code sent to',
    '个多组织账号已自动选择首个组织': ' multi-org accounts auto-selected first org',
    '个没识别到可用流派': ' accounts with unrecognized login method',
    '成功通过 Session Token 导入': 'Successfully imported via Session Token',
    '成功通过 Auth1 Token 导入': 'Successfully imported via Auth1 Token',
    '正在全量并发导入': 'Full concurrent import of',
    '正在全量并发登录': 'Full concurrent login of',
    '嗅探完成，正在全量并发导入': 'Detection complete, full concurrent import of',
    '嗅探完成，正在导入': 'Detection complete, importing',
    '正在识别': 'Identifying',
    '个账号的登录类型……': ' accounts login type...',
    '正在批量刷新': 'Batch refreshing',
    '正在刷新账号列表...': 'Refreshing account list...',
    '全部刷新完成！': 'All refresh completed!',
    '刷新完成（部分失败）': 'Refresh complete (partial failure)',
    '账号列表已刷新': 'Account list refreshed',
    '确定要删除选中的': 'Are you sure you want to delete the selected',
    '个账号吗？': ' accounts?',
    '源账户数量与目标邮箱数量不匹配': 'Source account count does not match target email count',
    '批量转让完成！成功': 'Batch transfer complete! Success',
    '批量转让完成': 'Batch transfer complete',
    '并发执行中...': 'Concurrent execution...',
    '当前页没有账号': 'No accounts on current page',
    '已取消选择本页': 'Deselected current page',
    '已选择本页': 'Selected current page',
    '自动重置: 重置了': 'Auto reset: reset',
    '个账号的积分': ' accounts credits',
    '账号的积分': 'account credits',
    '批量删除确认': 'Batch Delete Confirmation',
    '确认批量转让': 'Confirm Batch Transfer',
    '批量转让订阅': 'Batch Transfer Subscription',
    '批量转让说明': 'Batch Transfer Instructions',
    '批量更换订阅': 'Batch Change Subscription',
    '批量刷新状态': 'Batch Refresh Status',
    '批量更改分组': 'Batch Change Group',
    '导出选中账号': 'Export Selected Accounts',
    '选择本页账号': 'Select Page Accounts',
    '请先选择账号': 'Please select accounts first',
    '批量更新完成': 'Batch update complete',
    '批量导入失败': 'Batch import failed',
    '确认批量转让': 'Confirm Batch Transfer',
    '确认更改': 'Confirm Change',
    '确认转让': 'Confirm Transfer',
    '选择目标分组': 'Select target group',
    '将选中的': 'Move selected',
    '个账号移动到指定分组：': ' accounts to the specified group:',
    '确认批量删除': 'Confirm Batch Delete',
    '批量删除失败': 'Batch delete failed',
    '成功删除': 'Successfully deleted',
    '获取账单信息失败': 'Failed to get billing info',
    '刷新账号列表': 'Refresh account list',
    '虚拟卡生成': 'Virtual Card Generator',
    '自动重置': 'Auto Reset',
    '账号管理': 'Account Management',
    '分组管理': 'Group Management',
    '添加分组': 'Add Group',
    '默认分组': 'Default Group',
    '操作日志': 'Operation Logs',
    '统计信息': 'Statistics',
    '高级筛选': 'Advanced Filter',
    '搜索账号...': 'Search accounts...',
    '搜索账号': 'Search accounts',
    '排序方式': 'Sort By',
    '邮箱名称': 'Email',
    '创建时间': 'Created At',
    '已用积分': 'Used Credits',
    '剩余积分': 'Remaining Credits',
    'Token过期': 'Token Expires',
    '订阅到期': 'Subscription Expires',
    '套餐类型': 'Plan Type',
    '日配额剩余%': 'Daily Quota %',
    '周配额剩余%': 'Weekly Quota %',
    '日配额剩余': 'Daily Quota Remaining',
    '周配额剩余': 'Weekly Quota Remaining',
    '批量删除': 'Batch Delete',
    '添加账号': 'Add Account',
    '批量导入': 'Batch Import',
    '导出账号': 'Export Accounts',
    '标签管理': 'Tag Management',
    '刷新全部': 'Refresh All',
    '清除筛选': 'Clear Filters',
    '应用筛选': 'Apply Filters',
    '剩余额度': 'Remaining Quota',
    '总额度': 'Total Quota',
    '剩余天数': 'Days Remaining',
    '暂无账号数据': 'No account data',
    '暂无账号': 'No accounts',
    '添加第一个账号': 'Add your first account',
    '账号卡片区域': 'Account Cards Area',
    '取消已选': 'Clear Selection',
    '导入进度': 'Import progress',
    '登录进度': 'Login progress',
    '成功导入': 'Successfully imported',
    '个已登录': ' logged in',
    '其余失败': ', rest failed',
    '没有成功导入任何账号': 'No accounts imported successfully',
    '导入失败': 'Import failed',
    '添加失败': 'Add failed',
    '添加成功': 'Added successfully',
    '刷新失败': 'Refresh failed',
    '操作失败': 'Operation failed',
    '复制失败': 'Copy failed',
    '更新失败': 'Update failed',
    '删除失败': 'Delete failed',
    '检查失败': 'Check failed',
    '登录失败': 'Login failed',
    '迁移失败': 'Migration failed',
    '查询失败': 'Query failed',
    '重置失败': 'Reset failed',
    '切换账号失败': 'Switch account failed',
    '转让失败': 'Transfer failed',
    '升级失败': 'Upgrade failed',
    '未知错误': 'Unknown error',
    '正在刷新': 'Refreshing',
    '正在导入': 'Importing',
    '批量刷新': 'Batch refresh',
    '批量导出': 'Batch Export',
    '批量更新': 'Batch Update',
    '批量重置': 'Batch Reset',
    '批量操作': 'Batch Operations',
    '账号信息': 'Account Info',
    '编辑账号': 'Edit Account',
    '账号详情': 'Account Details',
    '积分详情': 'Credit Details',
    '配额详情': 'Quota Details',
    '基本信息': 'Basic Info',
    '本地信息': 'Local Info',
    '密钥管理': 'Key Management',
    '积分与配额': 'Credits & Quota',
    '团队详情': 'Team Details',
    '团队成员': 'Team Members',
    '邀请成员': 'Invite Members',
    '移除成员': 'Remove Member',
    '团队名称': 'Team Name',
    '团队设置': 'Team Settings',
    '团队邀请': 'Team Invitation',
    '团队管理': 'Team Management',
    '成员详情': 'Member Details',
    '席位管理': 'Seat Management',
    '更新座位': 'Update Seats',
    '添加标签': 'Add Tag',
    '编辑标签': 'Edit Tag',
    '删除标签': 'Delete Tag',
    '标签颜色': 'Tag Color',
    '标签名称': 'Tag Name',
    '新建标签': 'New Tag',
    '账单查询': 'Billing Query',
    '查询账单': 'Query Billing',
    '账单详情': 'Billing Details',
    '账单历史': 'Billing History',
    '支付信息': 'Payment Info',
    '付款周期': 'Payment Cycle',
    '支付周期': 'Payment Period',
    '付款周期选择': 'Payment Cycle Selection',
    '自动充值': 'Auto Recharge',
    '自动刷新': 'Auto Refresh',
    '无感换号': 'Seamless Switch',
    '深色模式': 'Dark Mode',
    '暗色主题': 'Dark Theme',
    '暗色模式': 'Dark Mode',
    '普通模式': 'Normal Mode',
    '无痕模式': 'Incognito Mode',
    '安装路径': 'Install Path',
    '检查更新': 'Check for Updates',
    '新版本': 'New Version',
    '跳过版本': 'Skip Version',
    '下载中': 'Downloading',
    '取消订阅': 'Cancel Subscription',
    '恢复订阅': 'Restore Subscription',
    '购买积分': 'Purchase Credits',
    '重新邀请': 'Re-invite',
    '智能识别': 'Smart Detection',
    '邮箱密码': 'Email/Password',
    '邮箱验证码': 'Email Verification Code',
    '登录方式': 'Login Method',
    '认证流派': 'Auth Provider',
    '注册来源': 'Registration Source',
    '注册时间': 'Registration Time',
    '完成注册': 'Complete Registration',
    '注册新账号': 'Register New Account',
    '输入邮箱': 'Enter email',
    '选择分组': 'Select Group',
    '发送验证码': 'Send Verification Code',
    '直接迁入': 'Direct Import',
    '备注信息': 'Remark Info',
    '每行一个': 'One per line',
    '测试账号': 'Test Account',
    '错误信息': 'Error Info',
    '确定删除': 'Confirm Delete',
    '确认删除': 'Confirm Delete',
    '模型名称': 'Model Name',
    '导入成功': 'Import successful',
    '直接成功': 'Direct success',
    '账号主归属': 'Account Primary Attribution',
    '不能为空': 'cannot be empty',
    '模式的验证规则': 'mode validation rules',
    '账号不存在': 'Account does not exist',
    '自动桥接': 'Auto Bridge',
    '原生注册': 'Native Registration',
    '目标邮箱': 'Target Email',
    '操作取消': 'Operation cancelled',
    '正在导入中...': 'Importing...',
    '虚拟卡': 'Virtual Card',
    '卡生成器': 'Card Generator',
    '生成卡片': 'Generate Cards',
    '卡片数量': 'Card Count',
    '批量重置团队积分': 'Batch Reset Team Credits',
    '重置积分': 'Reset Credits',
    '切换账号': 'Switch Account',
    '操作日志': 'Operation Logs',
    '日配额': 'Daily Quota',
    '周配额': 'Weekly Quota',
    '到期时间': 'Expiry Date',
    '已过期': 'Expired',
    '即将过期': 'Expiring soon',
    '已禁用': 'Disabled',
    '未激活': 'Inactive',
    '订阅未激活': 'Subscription inactive',
    '账户正常': 'Account normal',
    '被 Windsurf 禁用': 'Disabled by Windsurf',
    'Token 失效': 'Token invalid',
    '操作异常': 'Operation error',
    '点击复制: ': 'Click to copy: ',
    '通过 Devin Session 认证（新体系）': 'Authenticated via Devin Session (new system)',
    '复制邮箱': 'Copy email',
    '点击复制': 'Click to copy',
    '信用卡': 'Credit Card',
    '微信支付': 'WeChat Pay',
    '支付宝': 'Alipay',
    '试用资格': 'Trial Eligibility',
    '账号邮箱': 'Account Email',
    '显示结果': 'Show Results',
    '按钮样式': 'Button Style',
    '背景装饰': 'Background Decoration',
    '导出': 'Export',
    '导入中': 'Importing',
    '导入': 'Import',
    '请选择': 'Please select',
    '请输入': 'Please enter',
    '请粘贴': 'Please paste',
    '请添加': 'Please add',
    '确定': 'Confirm',
    '取消': 'Cancel',
    '删除': 'Delete',
    '编辑': 'Edit',
    '保存': 'Save',
    '关闭': 'Close',
    '确认': 'Confirm',
    '添加': 'Add',
    '刷新': 'Refresh',
    '设置': 'Settings',
    '搜索': 'Search',
    '返回': 'Back',
    '更新': 'Update',
    '复制': 'Copy',
    '粘贴': 'Paste',
    '重置': 'Reset',
    '全选': 'Select All',
    '完成': 'Done',
    '开始': 'Start',
    '停止': 'Stop',
    '启用': 'Enable',
    '禁用': 'Disable',
    '登录': 'Login',
    '注册': 'Register',
    '退出': 'Exit',
    '提交': 'Submit',
    '上传': 'Upload',
    '下载': 'Download',
    '切换': 'Switch',
    '查看': 'View',
    '清空': 'Clear',
    '清除': 'Clear',
    '加载': 'Loading',
    '加载中': 'Loading',
    '正在加载': 'Loading',
    '失败': 'failed',
    '成功': 'successful',
    '错误': 'Error',
    '警告': 'Warning',
    '提示': 'Notice',
    '信息': 'Info',
    '暂无': 'None',
    '未知': 'Unknown',
    '状态': 'Status',
    '邮箱': 'Email',
    '密码': 'Password',
    '账号': 'Account',
    '账户': 'Account',
    '用户': 'User',
    '名称': 'Name',
    '备注': 'Remark',
    '标签': 'Tags',
    '分组': 'Group',
    '团队': 'Team',
    '成员': 'Member',
    '席位': 'Seat',
    '权限': 'Permission',
    '角色': 'Role',
    '订阅': 'Subscription',
    '套餐': 'Plan',
    '积分': 'Credits',
    '配额': 'Quota',
    '额度': 'Quota',
    '充值': 'Recharge',
    '消耗': 'Consumed',
    '剩余': 'Remaining',
    '已用': 'Used',
    '总计': 'Total',
    '总': 'Total',
    '详情': 'Details',
    '操作': 'Operation',
    '管理': 'Management',
    '统计': 'Statistics',
    '分析': 'Analysis',
    '列表': 'List',
    '页面': 'Page',
    '对话框': 'Dialog',
    '模式': 'Mode',
    '功能': 'Feature',
    '关于': 'About',
    '版本': 'Version',
    '升序': 'Ascending',
    '降序': 'Descending',
    '最小': 'Min',
    '最大': 'Max',
    '全部': 'All',
    '部分': 'Partial',
    '正常': 'Normal',
    '离线': 'Offline',
    '在线': 'Online',
    '活跃': 'Active',
    '过期': 'Expired',
    '域名': 'Domain',
    '代理': 'Proxy',
    '服务器': 'Server',
    '客户端': 'Client',
    '密钥': 'Secret Key',
    '令牌': 'Token',
    '验证码': 'Verification Code',
    '验证': 'Verify',
    '时间': 'Time',
    '日期': 'Date',
    '天前': 'days ago',
    '小时前': 'hours ago',
    '分钟前': 'minutes ago',
    '刚刚': 'Just now',
    '天': 'days',
    '小时': 'hours',
    '分钟': 'minutes',
    '秒': 'seconds',
    '昵称': 'Nickname',
    '姓名': 'Name',
    '电话': 'Phone',
    '手机号': 'Phone Number',
    '地址': 'Address',
    '城市': 'City',
    '选择州': 'Select State',
    '月付': 'Monthly',
    '年付': 'Annually',
    '免费版': 'Free',
    '专业版': 'Pro',
    '企业版': 'Enterprise',
    '旗舰版': 'Flagship',
    '试用版': 'Trial',
    '团队版': 'Team',
    '紧凑版': 'Compact',
    '免费': 'Free',
    '专业': 'Pro',
    '企业': 'Enterprise',
    '标准': 'Standard',
    '高级': 'Advanced',
    '侧边栏': 'Sidebar',
    '顶部操作栏': 'Top Action Bar',
    '主内容区': 'Main Content',
    '内容': 'Content',
    '分页': 'Pagination',
    '每页': 'Per Page',
    '条': 'items',
    '总数': 'Total',
    '当前': 'Current',
    '开启': 'Enable',
    '数量不匹配': 'Count mismatch',
    '数量匹配': 'Count matched',
    '已输入': 'Entered',
    '个邮箱': ' emails',
    '个账号': ' accounts',
    '个失败': ' failed',
    '个成功': ' succeeded',
    '个': '',
    '还有': 'and',
    '失败账号': 'Failed accounts',
    '失败详情': 'Failure details',
    '转让后源账户将被移出团队': 'Source accounts will be removed from team after transfer',
    '此操作不可撤销': 'This action cannot be undone',
    '已选中': 'Selected',
    '个源账户需要转让订阅。': ' source accounts need subscription transfer.',
    '知道了': 'OK',
    '我知道了': 'OK',
    '用邮箱验证码登录': 'Login with email verification code',
    '企业 SSO 账号': 'Enterprise SSO Account',
    '账号未设置密码': 'Account has no password',
    '立即注册': 'Register Now',
    '账号受限': 'Account Restricted',
    '未知的嗅探结果': 'Unknown detection result',
    '补丁已升级': 'Patch upgraded',
    '补丁已是最新': 'Patch is up to date',
    '补丁已经应用过了': 'Patch already applied',
    '无感换号已': 'Seamless switch ',
    '开启': 'enabled',
    '关闭': 'disabled',
    '应用补丁': 'Apply patch',
    '还原补丁': 'Restore patch',
    'HTTP客户端已重置': 'HTTP client reset',
    '重置HTTP客户端': 'Reset HTTP Client',
    '重置失败': 'Reset failed',
    '伟哥功能': 'MCP Feature',
    '伟哥': 'MCP',
    '卸载伟哥': 'Uninstall MCP',
    '检查中': 'Checking',
    '已安装': 'Installed',
    '未安装': 'Not installed',
    '安装中': 'Installing',
    '运行中': 'Running',
    '已完成': 'Completed',
    '已取消': 'Cancelled',
    '已启用': 'Enabled',
    '已禁用': 'Disabled',
    '已移除': 'Removed',
    '已添加': 'Added',
    '已导出': 'Exported',
    '已删除': 'Deleted',
    '已复制': 'Copied',
    '已设置': 'Set',
    '已重置': 'Reset',
    '已生成': 'Generated',
    '已同步': 'Synced',
    '已验证': 'Verified',
    '未验证': 'Unverified',
    '已选择': 'Selected',
    '已配置': 'Configured',
    '已存在': 'Already exists',
    '已失效': 'Invalid',
    '已通过': 'Approved',
    '已拒绝': 'Rejected',
    '已批准': 'Approved',
    '已找到': 'Found',
    '已填写': 'Filled',
    '已输入': 'Entered',
    '已使用': 'Used',
    '未使用': 'Unused',
    '寸止': 'Rate Limit',
    '不一致': 'inconsistent',
    '缺少': 'Missing',
    '明天到期': 'Expires tomorrow',
    '今天到期': 'Expires today',
    '已到期': 'Expired',
    '上一步': 'Previous',
    '下一步': 'Next',
    '卡号': 'Card Number',
    '卡类型': 'Card Type',
    '有效期': 'Expiry',
    '张卡片': ' cards',
    '您暂无': 'You have no',
    '连接池': 'Connection Pool',
    '交流群': 'Community Group',
    '知识库': 'Knowledge Base',
    '请重启': 'Please restart',
    '新密码': 'New Password',
    '修改密码': 'Change Password',
    '输入新密码': 'Enter new password',
    '当前密码': 'Current Password',
    '保存设置': 'Save Settings',
    '投票数': 'Votes',
    '接受率': 'Acceptance Rate',
    '排行榜': 'Leaderboard',
    '趋势图': 'Trend Chart',
    '统计图': 'Statistics Chart',
    '使用量': 'Usage',
    '使用率': 'Usage Rate',
    '总配额': 'Total Quota',
    '消息数': 'Messages',
    '会话数': 'Sessions',
    '总积分数': 'Total Credits',
    '接受的代码行数': 'Accepted Lines of Code',
    '推荐人': 'Referrer',
    '被推荐人': 'Referree',
    '推荐码': 'Referral Code',
    '邀请码': 'Invite Code',
    '总席位': 'Total Seats',
    '座位数': 'Seat Count',
    '总费用': 'Total Cost',
    '计费策略': 'Billing Strategy',
    '计费周期': 'Billing Cycle',
    '缓存使用': 'Cache Usage',
    '缓存限制': 'Cache Limit',
    '积分记录': 'Credit History',
    '用户标志': 'User Flags',
    '禁用访问': 'Access Disabled',
    '成员名称': 'Member Name',
    '检测到': 'Detected',
    '开启后': 'After enabling',
    '启用后': 'After enabling',
    '位验证码': '-digit verification code',
    '请输入分组名称': 'Please enter group name',
    '分组名称': 'Group name',
    '分组名': 'Group name',
    '修改分组名称': 'Rename group',
    '重命名分组': 'Rename Group',
    '删除分组': 'Delete Group',
    '确定删除分组': 'Confirm delete group',
    '新分组名称': 'New group name',
    '正在登录': 'Logging in',
    '正在加载...': 'Loading...',
    '加载失败': 'Load failed',
    '加载更多': 'Load more',
    '无数据': 'No data',
    '暂无数据': 'No data available',
    '总体统计': 'Overall Statistics',
    '状态卡片': 'Status Card',
    '账号与': 'Account and',
    '待审批': 'Pending Approval',
    '已过期': 'Expired',
    '未指定': 'Not specified',
    '格式': 'format',
    '可选': 'Optional',
    '位数字': '-digit number',
    '最后更新': 'Last Updated',
    '可升级': 'Upgradable',
    '主组织': 'Primary Org',
    '拖拽排序': 'Drag to reorder',
    '数量': 'Count',
    # ============== SECOND PASS: remaining frequent terms ==============
    '获取': 'fetch',
    '数据': 'data',
    '使用': 'usage',
    '默认': 'default',
    '按钮': 'button',
    '选择': 'select',
    '按': 'by',
    '检查': 'check',
    '卡片': 'card',
    '显示': 'display',
    '是否': 'whether',
    '配置': 'config',
    '样式': 'style',
    '输入': 'input',
    '类型': 'type',
    '体系': 'system',
    '支持': 'support',
    '试用': 'trial',
    '模型': 'model',
    '邀请': 'invite',
    '如果': 'if',
    '分支': 'branch',
    '计划': 'plan',
    '解析': 'parse',
    '迁移': 'migrate',
    '结果': 'result',
    '直接': 'directly',
    '适配': 'adapt',
    '记录': 'record',
    '定时器': 'timer',
    '支付': 'payment',
    '进度': 'progress',
    '执行': 'execute',
    '所有': 'all',
    '通过': 'via',
    '自动': 'auto',
    '移除': 'remove',
    '生成': 'generate',
    '合并卡': 'merge card',
    '等待': 'wait',
    '循环': 'loop',
    '备份': 'backup',
    '创建': 'create',
    '反查': 'reverse lookup',
    '更换': 'change',
    '打开': 'open',
    '基础': 'basic',
    '迁入': 'import into',
    '并发': 'concurrent',
    '连续': 'consecutive',
    '路径': 'path',
    '允许': 'allow',
    '用于': 'used for',
    '表格': 'table',
    '立即': 'immediately',
    '处理': 'handle',
    '监听': 'listen',
    '方式': 'method',
    '账密': 'credentials',
    '原生': 'native',
    '全量并发': 'full concurrent',
    '隐私': 'privacy',
    '批量': 'batch',
    '转让': 'transfer',
    '访问': 'access',
    '筛选': 'filter',
    '包含': 'contains',
    '需要': 'need',
    '落库': 'persist to DB',
    '邮件': 'email',
    '后端': 'backend',
    '百分比': 'percentage',
    '有效': 'valid',
    '除以': 'divide by',
    '表单': 'form',
    '根据': 'based on',
    '选中': 'selected',
    '使用情况': 'usage info',
    '最后': 'last',
    '正在': 'currently',
    '字符串': 'string',
    '区域': 'area',
    '必须以': 'must start with',
    '规则': 'rules',
    '目标': 'target',
    '次数': 'count',
    '循环更换': 'cycle change',
    '一次': 'once',
    '填写': 'fill in',
    '恢复': 'restore',
    '模型配置': 'model config',
    '排序配置': 'sort config',
    '对应后端': 'corresponds to backend',
    '结构体': 'struct',
    '确保': 'ensure',
    '预览': 'preview',
    '机器': 'machine',
    '换取': 'exchange for',
    '原始': 'original',
    '前缀': 'prefix',
    '流程': 'flow',
    '激活': 'activate',
    '的颜色': ' color',
    '查找': 'find',
    '调用': 'call',
    '没有可': 'no available',
    '中打开': ' opened in',
    '注意': 'note',
    '浏览器': 'browser',
    '第三方': 'third-party',
    '完整': 'complete',
    '月度': 'monthly',
    '枚举': 'enum',
    '并落库': 'and persist to DB',
    '推荐': 'recommend',
    '选项': 'option',
    '说明': 'description',
    '响应': 'response',
    '测试': 'test',
    '待处理邀请': 'pending invitations',
    '申请加入': 'apply to join',
    '加入': 'join',
    '跳过': 'skip',
    '事件': 'event',
    '对应': 'corresponding',
    '滚动': 'scroll',
    '排序': 'sort',
    '底层接口': 'low-level API',
    '发送': 'send',
    '查询': 'query',
    '后续': 'subsequent',
    '已是': 'already is',
    '座位': 'seat',
    '是否为': 'whether it is',
    '补丁': 'patch',
    '触发': 'trigger',
    '组件': 'component',
    '检查是否': 'check if',
    '请先': 'please first',
    '自动填写表单': 'auto fill form',
    '颜色': 'color',
    '限制': 'limit',
    '开关': 'toggle',
    '跳转': 'redirect',
    '延迟': 'delay',
    '计算': 'calculate',
    '流派': 'provider type',
    '其他': 'other',
    '续期': 'renew',
    '前缀开头': 'prefix start',
    '智能': 'smart',
    '趋势': 'trend',
    '每日': 'daily',
    '销毁旧图表实例': 'destroy old chart instance',
    '强制重绘': 'force redraw',
    '使用次数': 'usage count',
    '初始化': 'initialize',
    '补全': 'autocomplete',
    '自定义': 'custom',
    '阈值': 'threshold',
    '映射': 'mapping',
    '全局': 'global',
    '日志': 'log',
    '重试次数': 'retry count',
    '卡段范围': 'card range',
    '到本地': 'to local',
    '接受邀请': 'accept invitation',
    '申请': 'apply',
    '邀请链接': 'invite link',
    '代码地图': 'code map',
    '无限': 'unlimited',
    '后端只': 'backend only',
    '本地': 'local',
    '组件卸载时': 'on component unmount',
    '区块': 'block',
    '计划类型': 'plan type',
    '原因': 'reason',
    '自动解析': 'auto parse',
    '认证': 'auth',
    '强制': 'force',
    '服务端向': 'server to',
    '供后续': 'for subsequent',
    '前置：调用方': 'prerequisite: caller',
    '拿到': 'obtained',
    '并引导': 'and guide',
    '读取邮件中的': 'read from email the',
    '多组织场景下': 'in multi-org scenario',
    '需调': 'need to call',
    '二次': 'secondary',
    '产品': 'product',
    '已存的明文': 'stored plaintext',
    '应用': 'apply',
    '防抖': 'debounce',
    '转换': 'convert',
    '动态': 'dynamic',
    '避免': 'avoid',
    '手动': 'manually',
    '占比': 'proportion',
    '红色': 'red',
    '文本': 'text',
    '将在': 'will be',
    '消息': 'message',
    '实际': 'actual',
    '尝试': 'try',
    '渲染': 'render',
    '分派': 'dispatch',
    '接口': 'API',
    '后自动': 'then auto',
    '构建': 'build',
    '自动接受邀请': 'auto accept invitation',
    '链接': 'link',
    '可能': 'possibly',
    '动画': 'animation',
    '正在获取': 'fetching',
    '推荐链接': 'referral link',
    '客户': 'customer',
    '计费': 'billing',
    '遥测': 'telemetry',
    '网络': 'network',
    '层级': 'hierarchy',
    '结束': 'end',
    '提供商': 'provider',
    '会话': 'session',
    '位小数': ' decimal places',
    '优先使用': 'prefer using',
    '优先从': 'prefer from',
    '否则从': 'otherwise from',
    '戳': 'timestamp',
    '下的': "'s",
    # ============== THIRD PASS: single chars and short fragments in comments ==============
    '化': '',
    '的': '',
    '和': ' and ',
    '或': ' or ',
    '已': 'already ',
    '位': '',
    '侧': ' side',
    '要': 'need to',
    '仅': 'only ',
    '相关': 'related',
    '在': 'in',
    '并': ' and ',
    '如': 'e.g.',
    '到': 'to',
    '新': 'new',
    '是': 'is',
    '值': 'value',
    '吗': '?',
    '页': 'page',
    '等': 'etc.',
    '走': 'use',
    '后': 'after',
    '池': 'pool',
    '无': 'no',
    '未': 'not',
    '此': 'this',
    '单': 'single',
    '次': 'time(s)',
    '为': 'as',
    '员': '',
    '该': 'the',
    '请': 'please',
    '调': 'call',
    '当': 'when',
    '月': 'month',
    '级': 'level',
    '第': '#',
    '每': 'every',
    '码': 'code',
    '主': 'primary',
    '只': 'only',
    '但': 'but',
    '了': '',
    '号': '',
    '多': 'multiple',
    '重新': 're-',
    '步': 'step',
    '旧': 'old',
    '有': 'has',
    '日': 'day',
    '聊': 'chat',
    '让': 'let',
    '名': 'name',
    '组': 'group',
    '中': 'in',
    '从': 'from',
    '数': 'count',
    '不': 'not',
    '再': 'again',
    '还': 'also',
    '它': 'it',
    '以': 'to',
    '逐': 'each',
    '对': 'for',
    '这些': 'these',
    '拿': 'get',
    '下': 'under',
    '及': 'and',
    '被': 'was',
    '可': 'can',
    '需': 'need',
    '做': 'do',
    '条': 'item(s)',
    '用': 'use',
    '其': 'its',
    '非': 'non-',
    '把': 'put',
    '则': 'then',
    '即': 'i.e.',
    '给': 'give',
    '上': 'on',
    '更': 'more',
    '之': 'of',
    '都': 'all',
    '最': 'most',
    '前': 'before',
    '里': 'in',
    '起': 'start',
    '也': 'also',
    '若': 'if',
    '同': 'same',
    '回': 'back',
    '会': 'will',
    '去': 'go',
    '再': 'again',
    '得': 'get',
    '些': 'some',
    '还是': 'or',
    '因为': 'because',
    '不走': 'do not use',
    '不调': 'do not call',
    '不再': 'no longer',
    '不需要': 'does not need',
    '不用': 'no need to',
    '外层': 'outer',
    '外环': 'outer loop',
    '内部': 'internal',
    '嵌套在': 'nested in',
    '子树': 'subtree',
    '子项': 'sub-item',
    '子流程': 'subprocess',
    '浮层': 'overlay',
    '对话': 'dialog',
    '折叠态': 'collapsed state',
    '宽度': 'width',
    '保持': 'keep',
    '脚本': 'script',
    '格式化': 'format',
    '对齐': 'align',
    '垂直居中': 'vertical center',
    '列表动画': 'list animation',
    '卡片式': 'card style',
    '紧凑': 'compact',
    '空状态': 'empty state',
    '左侧': 'left side',
    '右侧': 'right side',
    '图标': 'icon',
    '语言': 'language',
    '深色': 'dark',
    '浅色': 'light',
    '文件': 'file',
    '文件名': 'filename',
    '时区': 'timezone',
    '起始': 'start',
    '条目': 'entry',
    '键名': 'key name',
    '键盘': 'keyboard',
    '集成': 'integration',
    '汇总': 'summary',
    '合并': 'merge',
    '新增': 'add new',
    '清理': 'cleanup',
    '保留': 'keep',
    '日常': 'daily',
    '评分': 'score',
    '部署': 'deploy',
    '实现': 'implement',
    '解码': 'decode',
    '旗舰': 'flagship',
    '红': 'red',
    '绿色': 'green',
    '蓝色': 'blue',
    '灰色': 'gray',
    '橙色': 'orange',
    '浅蓝色': 'light blue',
    '浅紫色': 'light purple',
    '琥珀金': 'amber gold',
    '科技蓝': 'tech blue',
    '待办灰': 'pending gray',
    '入门版': 'Starter',
    '池化版': 'Pooled',
    '矮版': 'mini',
    '混合版': 'Hybrid',
    '页脚': 'footer',
    '固定': 'fixed',
    '响应式': 'responsive',
    '算法': 'algorithm',
    '兼容': 'compatible',
    '永远为': 'always',
    '可省略': 'can be omitted',
    '留空': 'leave empty',
    '默认值': 'default value',
    '倍率': 'multiplier',
    '倍数': 'multiple',
    '端口': 'port',
    '匿名': 'anonymous',
    '来源': 'source',
    '常用': 'common',
    '官方': 'official',
    '历史': 'history',
    '关联': 'associate',
    '反馈': 'feedback',
    '桥接': 'bridge',
    '接管': 'takeover',
    '去除': 'remove',
    '类名': 'class name',
    '大小': 'size',
    '风格': 'style',
    '无效': 'invalid',
    '过滤': 'filter',
    '修复': 'fix',
    '冲突': 'conflict',
    '拷贝': 'copy',
    '审查': 'review',
    '仅走': 'only use',
    '稍后': 'later',
    '仅需': 'only need',
    '回传': 'callback',
    '例如': 'e.g.',
    '至少': 'at least',
    '令牌': 'token',
    '失效': 'invalid',
    '链路': 'chain',
    '分类': 'category',
    '待定': 'pending',
    '命令': 'command',
    '动态': 'dynamic',
    '如果为': 'if is',
    '保存到': 'save to',
    '后再试': 'then try again',
    '分组名': 'group name',
    '与动作': 'and action',
    '让后续': 'let subsequent',
    '后端用': 'backend uses',
    '有原因': 'has reason',
    '传统': 'traditional',
    '聊天': 'chat',
    '浮层': 'overlay',
    '消除': 'eliminate',
    '开头': 'start with',
    '文档': 'document',
    '导入': 'import',
    '删除': 'delete',
    '重置': 'reset',
    '限制': 'limit',
    '获取': 'fetch',
    '年付': 'annually',
    '月付': 'monthly',
    '拿到': 'got',
    '小于': 'less than',
    '等待': 'wait',
    '尝试': 'try',
    '同意': 'agree',
    '接受': 'accept',
    '需要': 'need',
    '触发': 'trigger',
    '候补': 'waitlist',
    '进行': 'proceed',
    '未知': 'unknown',
    '同步': 'sync',
    '过期': 'expired',
    '浏览': 'browse',
    '建号': 'create account',
    '适合': 'suitable',
    '判定': 'determine',
    '胜率': 'win rate',
    '周期': 'cycle',
    '不走': 'not use',
    '校验': 'validate',
    '并发': 'concurrent',
    '文字': 'text',
    '只有': 'only when',
    '原始': 'original',
    '离线': 'offline',
    '穿透': 'penetrate',
    '匹配': 'match',
    '联邦': 'federal',
    '城市': 'city',
    '速度': 'speed',
    '切到': 'switch to',
    '后做': 'then do',
    '因为': 'because',
    '子树': 'subtree',
    '非空': 'non-empty',
    '检测': 'detect',
    '主号': 'primary account',
    '外层': 'outer layer',
    '使用': 'use',
    '成功': 'success',
    '需调': 'need to call',
    '池化': 'pooled',
    '认证': 'auth',
    '键盘': 'keyboard',
    '对齐': 'align',
    '切换': 'switch',
    '参考': 'reference',
    '避免': 'avoid',
    '呈现': 'render',
    '撤销': 'revoke',
    '形态': 'form',
    '每个': 'each',
    '全部': 'all',
    '确定': 'confirm',
    '字符': 'character',
    '分隔': 'delimiter',
    '留空': 'leave empty',
    '展开': 'expand',
    '一致': 'consistent',
    '过滤': 'filter',
    '注册': 'register',
    '仅走': 'only use',
    '稍后': 'later',
    '忘密': 'forgot password',
    '仅需': 'only need',
    '降序': 'descending',
    '升序': 'ascending',
    '内容': 'content',
    '变化': 'change',
    '格式': 'format',
    '解析': 'parse',
    '保持': 'maintain',
    '布尔值': 'boolean',
    '必须在': 'must be in',
    '必须是': 'must be',
    '必须': 'must',
    '列表项': 'list item',
    '分钟前': 'minutes ago',
    '分钟内': 'within minutes',
    '分钟后': 'minutes later',
    '分钟': 'minutes',
    '小时前': 'hours ago',
    '管理员': 'administrator',
    '白名单': 'whitelist',
    '自托管': 'self-hosted',
    '未激活': 'inactive',
    '银联卡': 'UnionPay card',
    '操作栏': 'action bar',
    '转换为': 'convert to',
    '启用后': 'after enabling',
    '布尔值': 'boolean',
    '响应的': 'response',
    '必须在': 'must be in',
    '未登录': 'not logged in',
    '列表项': 'list item',
    '接受率': 'acceptance rate',
    '分流弹': 'routing popup',
    '用于从': 'used from',
    '管理员': 'admin',
    '前缀的': 'prefixed',
    '优先从': 'prefer from',
    '侧注册': 'side register',
    '卡类型': 'card type',
    '知识库': 'knowledge base',
    '与动作': 'and action',
    '让后续': 'let subsequent',
    '后端用': 'backend uses',
    '已完成': 'completed',
    '已选择': 'selected',
    '原来的': 'original',
    '嗅探失败': 'Detection failed',
    '嗅探': 'detection',
    '图表': 'chart',
    '实例': 'instance',
    '保存一次': 'save once',
    '拖拽': 'drag',
    '标题': 'title',
    # ============== FOURTH PASS: individual characters and mixed fragments =============
    'drag手柄': 'drag handle',
    '简单Version': 'simple version',
    '整合in': 'integrated in',
    '内': 'inside',
    '一排button': 'first row buttons',
    '二排button': 'second row buttons',
    '一键切': 'quick switch',
    '切progress': 'switch progress',
    '弹窗': 'dialog',
    '独立居in': 'standalone in',
    '居in': 'in',
    'Running禁止': 'running disabled',
    '禁止via': 'disabled via',
    'forceUser看to全flow': 'force user to watch full flow',
    '看to': 'watch',
    'successful/failed时': 'when success/failed',
    '时allow': 'allow when',
    '横向progressitems': 'horizontal progress items',
    '且': 'and',
    '绿': 'green',
    'itsit': 'other',
    'Current阶段描述': 'current stage description',
    'running 期间notgive任何button': 'no buttons during running',
    '期间not': 'no',
    'forceUserwaitbackend': 'force user wait backend',
    'non- running displaydisabled': 'non-running display disabled',
    '切': 'switch',
    '步': 'step',
    'prepareAccount Info': 'prepare account info',
    'fetch #一带colorTags': 'fetch first colored tag',
    '遍历AccountTags': 'iterate account tags',
    '找to': 'find',
    'card边框style': 'card border style',
    '边框透明度': 'border transparency',
    '发光效果透明度': 'glow effect transparency',
    '判断whether it is付费plan': 'check if it is paid plan',
    '时display': 'display when',
    'when付费plan且': 'when paid plan and',
    '为false': 'is false',
    '时才': 'only then',
    'checkAccountDisableStatus': 'check account disabled status',
    '尚notStart': 'not started yet',
    'not命inalready 知': 'unknown',
    '命': 'named',
    'Tauri eventlisten句柄': 'Tauri event listener handle',
    'everytime(s)点击切时new建': 'create new every time when clicking switch',
    'new建': 'create',
    '弹窗disabled or 卸载时释放': 'release when dialog closed or unmounted',
    '卸载时': 'when unmount',
    'manuallydisabled弹窗': 'manually close dialog',
    'only innon- running 阶段allow': 'only allow in non-running stage',
    'back退toAccountSave color': 'fallback to account saved color',
    'if没has找tocolor': 'if no color found',
    '而notis空for象': 'instead of being empty',
    '背景色use低透明度': 'background uses low transparency',
    '边框use稍高透明度': 'border uses slightly higher transparency',
    'ifcolorparsefailed': 'if color parse failed',
    'trydirectlyusecolorvalue': 'try directly use color value',
    'whetherhas带colorTags': 'whether has colored tags',
    '任意Tagswhetherhascolor': 'any tag whether has color',
    'level别': 'level',
    '作ascard边框色': 'as card border color',
    '与backend': 'with backend',
    'align': 'align',
    'before端by key': 'frontend by key',
    'findCurrentstep骤in序列in置来render': 'find current step position to render',
    'in置': 'position',
    'every一stepin UI onStatus': 'every step in UI status',
    '显式泛型声明': 'explicit generic declaration',
    'avoid TS insubsequent赋value': 'avoid TS subsequent assignment',
    'then do literal narrowing': 'then do literal narrowing',
    '使get': 'make get',
    'was错判asalways true': 'was wrongly judged as always true',
    '比较': 'compare',
    'step骤定义': 'step definition',
    '顺序与backend emit': 'sequence with backend emit',
    'step key maintainconsistent': 'step key maintain consistent',
    'Currentstep骤索引': 'current step index',
    '尚not': 'not yet',
    'Start': 'start',
    'not命inalready 知 step': 'unknown step',
    '命in': 'named',
    'already 知': 'known',
    'every一': 'every',
    'in UI': 'in UI',
    'onStatus': 'on status',
    '句柄': 'handle',
    '句': 'sentence',
    '柄': 'handle',
    'everytime(s)': 'every time',
    'time(s)': 'time',
    '点击切时': 'click switch time',
    'or 卸载时释放': 'or release when unmount',
    'avoid"路由Switch → component销毁 → event继续trigger"导致内存泄漏': 'avoid "route switch → component destroy → event continue trigger" causing memory leak',
    'avoid"': 'avoid "',
    '路由Switch': 'route switch',
    'component销毁': 'component destroy',
    '销毁': 'destroy',
    'event继续trigger': 'event continue trigger',
    '继续': 'continue',
    '导致': 'cause',
    '内存泄漏': 'memory leak',
    '内存': 'memory',
    '泄漏': 'leak',
    'only in': 'only in',
    'non- running': 'non-running',
    '阶段allow': 'stage allow',
    '服务端': 'server',
    '服务': 'service',
    '端': 'side',
    '时': 'when',
    '字段': 'field',
    '与': 'and',
    '将': 'will',
    '代': 'code',
    '织': 'org',
    '行': 'row',
    '一': 'one',
    '选': 'select',
    '点击': 'click',
    '器': 'manager',
    '没': 'no',
    '法': 'way',
    '重启': 'restart',
    '先': 'first',
    '工具': 'tool',
    '结构': 'structure',
    '场景': 'scenario',
    '额外': 'extra',
    '象': 'object',
    '存': 'save',
    '优': 'optimal',
    '字': 'character',
    '项': 'item',
    '期': 'period',
    '卡': 'card',
    '空': 'empty',
    '账': 'account',
    '列': 'column',
    '拒绝': 'reject',
    '辅助函': 'helper function',
    '函': 'function',
    '题': 'topic',
    '运行': 'run',
    '变': 'change',
    '复': 'complex',
    '由': 'by',
    '原': 'original',
    '类': 'class',
    '两': 'two',
    '详细': 'detailed',
    '头部': 'header',
    '本': 'this',
    '明确': 'clear',
    '范围': 'range',
    '绑卡': 'bind card',
    '适': 'suitable',
    '找': 'find',
    '带': 'with',
    '首': 'first',
    '窗口': 'window',
    '否': 'no',
    '快速': 'quick',
    '分享': 'share',
    '系统': 'system',
    '重试': 'retry',
    '贡献': 'contribute',
    '随机': 'random',
    '卡头': 'card header',
    '汇': 'summary',
    '覆盖': 'cover',
    '见': 'see',
    '圆形': 'circle',
    '容器': 'container',
    '任何': 'any',
    '求': 'require',
    '作': 'make',
    '判断': 'judge',
    '付费': 'paid',
    '统一': 'unify',
    '改': 'change',
    '人': 'person',
    '超时': 'timeout',
    '授予': 'grant',
    '我': 'I',
    '设': 'set',
    '隐藏': 'hide',
    '置': 'set',
    '框': 'box',
    '嵌套': 'nest',
    '展示': 'show',
    '建': 'build',
    '存储': 'store',
    '目': 'item',
    '文案': 'text',
    '传': 'pass',
    '排除自己': 'exclude self',
    '剪贴板': 'clipboard',
    '您': 'you',
    '共': 'total',
    '识别': 'identify',
    '正确': 'correct',
    '元': 'element',
    '顺序': 'order',
    '空格': 'space',
    '占': 'occupy',
    '时将': 'will',
    '普通': 'normal',
    '修改': 'modify',
    '率': 'rate',
    '自己': 'self',
    '性': 'property',
    '面板': 'panel',
    '整': 'whole',
    '菜': 'menu',
    '弹出': 'popup',
    '块': 'block',
    '试': 'try',
    '显': 'show',
    '能': 'can',
    '连接': 'connect',
    '方法': 'method',
    '拉': 'pull',
    '继续': 'continue',
    '现': 'now',
    '轻量': 'lightweight',
    '弹': 'popup',
    '发': 'send',
    '取': 'get',
    '因': 'because',
    '态': 'state',
    '通': 'through',
    '优先': 'priority',
    '网格': 'grid',
    '顶部': 'top',
    '过': 'pass',
    '进入': 'enter',
    '长度': 'length',
    '缓存': 'cache',
    '收集': 'collect',
    '分布': 'distribution',
    '字节': 'byte',
    '金额': 'amount',
    '美元': 'USD',
    '间隔': 'interval',
    '版': 'version',
    '区': 'area',
    '独立': 'independent',
    '底部': 'bottom',
    '异常': 'exception',
    '轮': 'round',
    '外部': 'external',
    '升': 'up',
    '三项子': 'three child items',
    '安装': 'install',
    '待': 'wait',
    '变量': 'variable',
    '队列': 'queue',
    '标记': 'mark',
    '产生字节': 'generate bytes',
    '凭证': 'credential',
    '任务': 'task',
    '元素': 'element',
    '线': 'line',
    '骤': 'step',
    '背景': 'background',
    '近': 'near',
    '属于': 'belongs to',
    '仍': 'still',
    '工作': 'work',
    '称': 'call',
    '忘记': 'forget',
    '面': 'side',
    '出': 'out',
    '归属': 'belong',
    '遇': 'meet',
    '本软件': 'this software',
    '勿': 'do not',
    '途': 'way',
    '别': 'other',
    '遍历': 'iterate',
    '使': 'use',
    '表示': 'represent',
    '读取': 'read',
    '增强': 'enhance',
    '注入': 'inject',
    '决定': 'decide',
    '始终': 'always',
    '资格': 'qualification',
    '样': 'sample',
    '布局': 'layout',
    '图': 'chart',
    '法继续': 'cannot continue',
    '谨慎': 'careful',
    '毫': 'milli',
    '经': 'through',
    '自助': 'self-service',
    '题色': 'theme color',
    '子': 'child',
    '老': 'old',
    '完全': 'complete',
    '织场景复': 'org scenario reuse',
    '形式': 'form',
    '建议代': 'suggested code',
    '聚合': 'aggregate',
    '预算': 'budget',
    '件': 'item',
    '概览': 'overview',
    '长': 'long',
    '混合': 'mix',
    '计入': 'include in',
    '计': 'count',
    '直': 'direct',
    '终': 'end',
    '持卡人': 'cardholder',
    '应': 'should',
    '内置': 'built-in',
    '相': 'mutual',
    '排除': 'exclude',
    '拥': 'own',
    '集': 'set',
    '审批': 'approve',
    '接收': 'receive',
    '文': 'text',
    '就绪': 'ready',
    '唯一': 'unique',
    '出现': 'appear',
    '开发': 'develop',
    '参与': 'participate',
    '保证': 'ensure',
    '空间': 'space',
    '右键菜': 'right click menu',
    '试快捷键': 'try shortcut',
    '启动': 'launch',
    '徽章': 'badge',
    '白色背景': 'white background',
    '内联': 'inline',
    '方案': 'solution',
    '指定': 'specify',
    '织时': 'when org',
    '求体': 'require body',
    '携带': 'carry',
    '既': 'both',
    '向': 'toward',
    '互转': 'mutual convert',
    '方': 'side',
    '传入': 'pass in',
    '某': 'certain',
    '赞助': 'sponsor',
    '微信扫': 'WeChat scan',
    '特性': 'feature',
    '供学习交流': 'for learning and exchange',
    '忽略': 'ignore',
    '手柄': 'handle',
    '看': 'look',
    '全': 'full',
    '退': 'back',
    '而': 'but',
    '边框': 'border',
    '赋': 'assign',
    '准备': 'prepare',
    '销毁': 'destroy',
    '阶段': 'stage',
    '足': 'enough',
    '空白': 'blank',
    '注': 'note',
    '分流': 'distribute',
    '写': 'write',
    '包括': 'include',
    '库': 'library',
    '时出错': 'error when',
    '付费签约': 'paid subscription',
    '均': 'all',
    '感': 'sense',
    '防止': 'prevent',
    '兜底': 'fallback',
    '属性': 'attribute',
    '点': 'point',
    '悬浮': 'hover',
    '美展示': 'beautiful display',
    '公开资料': 'public information',
    '移': 'move',
    '归因': 'attribution',
    '视': 'view',
    '折叠': 'collapse',
    '开发者': 'developer',
    '身份': 'identity',
    '排': 'row',
    '很大': 'very large',
    '备': 'prepare',
    '小': 'small',
    '美': 'beautiful',
    '高于': 'higher than',
    '特殊': 'special',
    '换行': 'newline',
    '相比': 'compared to',
    '区分': 'distinguish',
    '专属': 'exclusive',
    # ============== FIFTH PASS: remaining common fragments =============
    '询问': 'ask',
    '合格': 'qualified',
    '疑似': 'suspected',
    '解': 'solve',
    '签': 'sign',
    '报错': 'error report',
    '误报': 'false positive',
    '残留': 'residual',
    '触碰': 'touch',
    '防御': 'defense',
    '广播': 'broadcast',
    '们': 's',
    '瞬间': 'instant',
    '销': 'cancel',
    '双': 'double',
    '晚于': 'later than',
    '抵达': 'arrive',
    '断言绕开': 'assert bypass',
    '错认': 'misidentify',
    '加流畅': 'more smooth',
    '业务': 'business',
    '很少': 'rarely',
    '雅': 'elegant',
    '浮': 'float',
    '银': 'silver',
    '简约': 'simple',
    '醒': 'awake',
    '翡翠': 'jade',
    '活力': 'vibrant',
    '幻彩紫，尊贵': 'phantom purple, noble',
    '流光': 'flowing light',
    '宽': 'width',
    '读': 'read',
    '球': 'ball',
    '商': 'merchant',
    '身': 'body',
    '释': 'release',
    '脱敏': 'desensitize',
    '大': 'large',
    '假': 'fake',
    '型': 'type',
    '策略': 'strategy',
    '关键': 'key',
    '节': 'section',
    '觉偏差': 'perception bias',
    '沉': 'sink',
    '右栏': 'right column',
    '挤压': 'squeeze',
    '轴': 'axis',
    '载': 'load',
    '鼠标悬停': 'mouse hover',
    '协议': 'protocol',
    '填入': 'fill in',
    '满量': 'full capacity',
    '快捷': 'shortcut',
    '度': 'degree',
    '承载': 'carry',
    '觉': 'feel',
    '追加': 'append',
    '佳': 'good',
    '另': 'another',
    '窜': 'cross',
    '反骨': 'rebel',
    '约束': 'constraint',
    '定宽容度': 'set tolerance',
    '三路': 'three way',
    '抽': 'extract',
    '哪': 'which',
    '派': 'dispatch',
    '指引': 'guide',
    '提供快捷': 'provide shortcut',
    '依赖': 'depend',
    '转义': 'escape',
    '快捷引导': 'shortcut guide',
    '马': 'immediately',
    '瑕疵': 'flaw',
    '屏': 'screen',
    '引导': 'guide',
    '三种': 'three types',
    '刚': 'just',
    '递归': 'recursive',
    '修正': 'correct',
    '纵': 'vertical',
    '鼠标悬停：浅': 'mouse hover: light',
    '极浅': 'very light',
    '浅': 'light',
    '频繁省略': 'frequently omit',
    '收缩，跟': 'shrink, follow',
    '勾': 'hook',
    '右': 'right',
    '高度': 'height',
    '压': 'press',
    '窗': 'window',
    '撑穷': 'poor support',
    '采纳': 'adopt',
    '乘': 'multiply',
    '引': 'quote',
    '累': 'accumulate',
    '暴露': 'expose',
    '关，所': 'close, so',
    '落': 'fall',
    '早返': 'early return',
    '側效': 'side effect',
    '模板层拦截': 'template layer intercept',
    '量阈': 'threshold',
    '偶': 'occasional',
    '双连': 'double connect',
    '段': 'segment',
    '符间': 'between symbols',
    '干扰': 'interfere',
    '合理': 'reasonable',
    '遮蔽': 'shield',
    '左': 'left',
    '浅灰': 'light gray',
    '背高亮': 'back highlight',
    '式声明': 'declaration',
    '载于': 'load in',
    '灰': 'gray',
    '间短暂': 'brief interval',
}

def translate_file(filepath: Path) -> int:
    """Replace Chinese strings in a file. Returns number of replacements."""
    try:
        content = filepath.read_text(encoding='utf-8')
    except Exception:
        return 0

    original = content

    # Sort by length desc so longer phrases get matched first
    sorted_items = sorted(TRANSLATIONS.items(), key=lambda x: len(x[0]), reverse=True)

    for zh, en in sorted_items:
        content = content.replace(zh, en)

    if content != original:
        filepath.write_text(content, encoding='utf-8')
        return 1
    return 0


def main():
    changed = 0
    total = 0
    for root, dirs, files in os.walk(SRC_DIR):
        for file in files:
            if not file.endswith(('.vue', '.ts', '.tsx', '.js')):
                continue
            filepath = Path(root) / file
            total += 1
            if translate_file(filepath):
                changed += 1
                print(f"  [UPDATED] {filepath.relative_to(SRC_DIR.parent)}")

    print(f"\nProcessed {total} files, updated {changed} files.")


if __name__ == '__main__':
    main()
